export const ITEM_LIST_REQUEST="ITEM_LIST_REQUEST"
export const ITEM_LIST_SUCCESS="ITEM_LIST_SUCCESS"
export const ITEM_LIST_FAIL="ITEM_LIST_FAIl"


export const DETAIL_ITEM_REQUEST="DETAIL_ITEM_REQUEST"
export const DETAIL_ITEM_SUCCESS="DETAIL_ITEM_SUCCESS"
export const DETAIL_ITEM_FAIL="DETAIL_ITEM_FAIL"

export const REMOVE_ITEM_REQUEST="REMOVE_ITEM_REQUEST"
export const REMOVE_ITEM_SUCCESS="REMOVE_ITEM_SUCCESS"
export const REMOVE_ITEM_FAIL="REMOVE_ITEM_FAIL"

export const ADD_ITEM_REQUEST="ADD_ITEM_REQUEST"
export const ADD_ITEM_SUCCESS="ADD_ITEM_SUCCESS"
export const ADD_ITEM_FAIL="ADD_ITEM_FAIL"